### ISSUE TITLE
Proposal: preview builds (Netlify or Zeit)

### ISSUE THREAD

**Issue by DanielRuf** [verdaccio/website#128]
As a contributor I want to see a preview of the changes in my PRs and branches using Netlify or Zeit.

Reference: https://github.com/DanielRuf/website/pull/1

**Comment by juanpicado** [comment]
Netlify +1

**Comment by DanielRuf** [comment]
@juanpicado let's check what we need to use this.

I guess we have to setup the Netlify integration including for PRs and then test on a separate branch.

**Comment by juanpicado** [comment]
Sure, let me know whether I can help with some step of this.

**Comment by juanpicado** [comment]
https://github.com/verdaccio/website/pull/270
