### ISSUE TITLE
 Installing on IIS server needs to be updated to work with v3.x

### ISSUE THREAD

**Issue by mlamothe** [verdaccio/website#19]
The [Installing on IIS](https://verdaccio.org/docs/en/iss-server) server instructions haven't been updated for Verdaccio v3.x.

I'm not sure if this is the official way to do it, but when upgrading from 2.x to 3.x, I needed to change start.js from:

```
process.argv.push('-l', 'unix:' + process.env.PORT);
require('./node_modules/verdaccio/src/lib/cli.js');

```
To:

```
process.argv.push('-l', 'unix:' + process.env.PORT);
require('./node_modules/verdaccio/build/lib/cli.js');
```

**Comment by juanpicado** [comment]
Totally valid bug . Could you PR,?
