### ISSUE TITLE
Contributing page contains a broken image

### ISSUE THREAD

**Issue by PDavid** [verdaccio/website#205]
The "I can do translations" section contains an image which is not displayed.
Instead 403 - Forbidden is returned for the URL: https://d3n8a8pro7vhmx.cloudfront.net/uridu/pages/144/attachments/original/1485948891/Crowdin.png

**Comment by DanielRuf** [comment]
The link to the affected page is https://verdaccio.org/docs/en/contributing

**Comment by DanielRuf** [comment]
Not sure what we should see there as wayback machine and Google Cache do not have the (old) version.

@juanpicado do you know what we should see there?

**Comment by juanpicado** [comment]
I think https://github.com/verdaccio/verdaccio/tree/master/assets/thanks/crowdin the crowdin logo.

**Comment by PDavid** [comment]
I found this image URL is in the contributing.md files under `website/website/translated_docs` .

I thought that I could fix this but I read this in https://github.com/verdaccio/website/blob/master/CONTRIBUTING.md file:
> Do not update files in the following folders due are autogenerated by crowdin
>   * `website/website/translated_docs` 

So can this be fixed by editing these files or should this be fixed on crowdin maybe?

**Comment by juanpicado** [comment]
`contributing.md` file was removed while ago ... it only exist in one version. I think you can go to crowdin and update it but won't be deployed anyway.

**Comment by PDavid** [comment]
@juanpicado Thanks for the response. Then I guess this issue can be closed. 👍

**Comment by juanpicado** [comment]
Thanks @PDavid for report it :-) ... if you find something else just let me know we can fix it.
