### ISSUE TITLE
bad/missing doc for "Understanding Scopes".  https://verdaccio.org/docs/en/scope

### ISSUE THREAD

**Issue by realfreebird** [verdaccio/website#213]
["Understanding Scopes"](https://verdaccio.org/docs/en/scopes)  documentation is empty.

![scopes](https://user-images.githubusercontent.com/17299389/69914033-32297500-1448-11ea-9da3-a79e91b0ad8e.jpg)

**Comment by DanielRuf** [comment]
Hi @realfreebird,

are you interested to provide a PR for this?

**Comment by realfreebird** [comment]
Hi @DanielRuf,
Unfortunately I can't do it at the moment.
