### ISSUE TITLE
Remove <div id="codefund">''</div>

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/website#271]
Within `docs/` many Mardown files still have `<div id="codefund">''</div>` .

The reason of this was to display ads, but we don't have them anymore.

Currently there is 32 matches within `/docs/*`.

**Comment by juanpicado** [comment]
cc: @marconipoveda 👍

**Comment by marconipoveda** [comment]
Thanks @juanpicado, I'm already on it.

**Comment by marconipoveda** [comment]
you were very specific "within `docs/`" right?

I found 700+ appearances of the code chunk across the project. I did what you asked "within `docs/`" 🌵

**Comment by juanpicado** [comment]
Yes, the others are translated by crowdin, so as long I merge this, the others will be removed automatically.
