### ISSUE TITLE
Documentation for AWS installation

### ISSUE THREAD

**Issue by gabrielenosso** [verdaccio/website#6]
Is there any documentation on how to install and run Verdaccio on AWS? (EC2, ECS, Elastic Beanstalk or whatever?)

I would love to introduce Verdaccio in my company, and a cloud installation would be perfect.

**Comment by juanpicado** [comment]
We are creating a new structure in the website (⚠️ perhaps you have noticed I relocated this issue to a new repo).

There is a page dedicated to amazon topics (https://github.com/verdaccio/website/blob/master/docs/amazon.md)

deployed here
https://hidden.verdaccio.org/docs/en/next/amazon

Feel free to contribute if you consider.

**Comment by odahcam** [comment]
@apexskier AWS claims that that policy needs a principal, do you created a specific user for that? Is there any need to setup authentication when a principal is added?

**Comment by apexskier** [comment]
@odahcam I don't know enough about AWS or AWS permissions to really know the answer to your question, but I suspect my organization has the principle set to an IAM role instead of a specific user that's shared across the org in some way.

**Comment by odahcam** [comment]
So I think I'll have to guess this in some way. 😆

**Comment by juanpicado** [comment]
FYI https://verdaccio.org/docs/en/next/amazon

**Comment by DanielRuf** [comment]
Released / part of the current docs: https://verdaccio.org/docs/en/amazon

Is this issue still relevant?

**Comment by juanpicado** [comment]
Yes, perhaps we need more insights here.
