### ISSUE TITLE
Put registry config on website

### ISSUE THREAD

**Issue by adjenks** [verdaccio/website#63]
I recommend you put this command on your website:

npm set registry http://localhost:4873/

It's only in the git repo and not on the website as well

**Comment by JayaKrishnaNamburu** [comment]
Hey, @juanpicado I would like to give a PR for this, any idea where you want to add this command, I would personally prefer above this line "That’s it! Enjoy your private package manager." so the flow goes like

1. First globally install it
2. Then you can set the local registry to point to this port and you can unset it whenever needed.

I like the project so much and had a good time using it, would like to do something in return :smile:

**Comment by juanpicado** [comment]
Thanks @JayaKrishnaNamburu  ! Here an idea. 

![Installation_·_Verdaccio](https://user-images.githubusercontent.com/558752/56131317-6159a780-5f87-11e9-85cd-6fe683ebeb95.png)

https://github.com/verdaccio/website/blob/master/docs/what-is-verdaccio.md

For the front end, give it a try, not sure about that, but feel free to PR we can discuss the style there and whether looks good or not. That par is on React, you can find more info here https://docusaurus.io/

**Comment by JayaKrishnaNamburu** [comment]
Sure, will look into this and update you in a while 😄

**Comment by DanielRuf** [comment]
Closing as the related PR is already merged.

https://github.com/verdaccio/website/pull/78#issuecomment-483521893
