### ISSUE TITLE
Small fault on installation page

### ISSUE THREAD

**Issue by robsch** [verdaccio/website#66]
```
$> verdaccio
warn --- config file  - /home/.config/verdaccio/config.yaml
warn --- http address - http://localhost:4873/ - verdaccio/3.0.0
```

Should be `/home/verdaccio/.config/config.yaml`.

**Comment by juanpicado** [comment]
That might depends of your environment, but, on MAC is  `ls -lsa ~/.config/verdaccio/config.yaml `. Could you give us a bit more if your set up?

**Comment by robsch** [comment]
Ah, okay. Verdaccio is on my Fedora VM. I cannot check this on my Mac (not being admin). But when I look on my Mac I see a folder `/home/robert/.config`, currenlty containing one folder for inkscape. Does the .config folder not being used for Verdaccio?

Close this ticket, if it does not make sense for you. No problem.
