### ISSUE TITLE
Refactor User Page

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/website#74]
I'd like to distribute our known users specially those are Open Source and separate them from companies. Something like this.

https://docusaurus.io/en/users

Currently we display some of them, but not well organised. 

https://verdaccio.org/en/users.html
https://verdaccio.org/docs/en/who-is-using

A PR will include logos of all those OSS projects, links to their pages. 

I want to display on front-end all OSS in first place, and second place only current official sponsors. Only one, SheetJS at this point.

**Comment by duncandean** [comment]
I'll see what I can do about this. 😃
