### ISSUE TITLE
Dead link and outdated kubernetes documentation

### ISSUE THREAD

**Issue by benharold** [verdaccio/website#88]
On the [Kubernetes page](https://verdaccio.org/docs/en/kubernetes#prepare) there's a link to: [existing configuration](https://github.com/verdaccio/verdaccio/blob/master/conf/full.yaml) which is deprecated. It also recommends to `wget` that file, which just has comments to visit https://verdaccio.org/docs/en/configuration

**Comment by juanpicado** [comment]
Yes, we should update that to refer the documentation. Would you like to PR?

**Comment by benharold** [comment]
👍 I will give it a shot when I get a bit of free time.

**Comment by DanielRuf** [comment]
Hi @benharold,

you might have much to do but I wanted to check if you have this still on your todo list =)

**Comment by benharold** [comment]
Sorry for the delay! https://github.com/verdaccio/website/pull/144

**Comment by juanpicado** [comment]
Thanks @benharold !!
